### ISSUE TITLE
 paramiko.ssh_exception

### ISSUE THREAD

**Issue by EvanJo** [iangow/wrds2pg#20]
Error: paramiko.ssh_exception.SSHException: Server 'wrds-cloud...' not found in known_hosts

**Comment by iangow** [comment]
1. Deleted WRDS server from `known_hosts`.

```
(base) iangow@Ians-Mac-mini wrds_pg % vim ~/.ssh/known_hosts
```

2. Tried updating table. Got an error message.

```
(base) iangow@Ians-Mac-mini wrds_pg % psql
psql (13.2)
Type "help" for help.

crsp=# DROP TABLE crsp.dsi;
DROP TABLE
crsp=# \q
(base) iangow@Ians-Mac-mini wrds_pg % python 
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:00:30) 
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from wrds2pg import wrds_update
>>> wrds_update("dsi", "crsp")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/iangow/miniforge3/lib/python3.9/site-packages/wrds2pg/wrds2pg.py", line 450, in wrds_update
    modified = get_modified_str(table_name, schema, wrds_id, encoding=encoding)
  File "/Users/iangow/miniforge3/lib/python3.9/site-packages/wrds2pg/wrds2pg.py", line 310, in get_modified_str
    p = get_process(sas_code, wrds_id)
  File "/Users/iangow/miniforge3/lib/python3.9/site-packages/wrds2pg/wrds2pg.py", line 26, in get_process
    client.connect('wrds-cloud.wharton.upenn.edu',
  File "/Users/iangow/miniforge3/lib/python3.9/site-packages/paramiko/client.py", line 415, in connect
    self._policy.missing_host_key(
  File "/Users/iangow/miniforge3/lib/python3.9/site-packages/paramiko/client.py", line 823, in missing_host_key
    raise SSHException(
paramiko.ssh_exception.SSHException: Server 'wrds-cloud.wharton.upenn.edu' not found in known_hosts
>>> exit()
```

3. Installed new version of package.

```
(base) iangow@Ians-Mac-mini wrds_pg % sudo -H pip3 install git+https://github.com/iangow/ling_features --upgrade

(base) iangow@Ians-Mac-mini wrds_pg % pip uninstall wrds2pg
Found existing installation: wrds2pg 1.0.7
Uninstalling wrds2pg-1.0.7:
  Would remove:
    /Users/iangow/miniforge3/lib/python3.9/site-packages/wrds2pg-1.0.7.dist-info/*
    /Users/iangow/miniforge3/lib/python3.9/site-packages/wrds2pg/*
Proceed (y/n)? y
  Successfully uninstalled wrds2pg-1.0.7
(base) iangow@Ians-Mac-mini wrds_pg % pip install git+https://github.com/iangow/wrds2pg          
Collecting git+https://github.com/iangow/wrds2pg
  Cloning https://github.com/iangow/wrds2pg to /private/var/folders/8g/9lwz95kd5wxdnhlvd6514ss00000gn/T/pip-req-build-rq_ek2li
  Running command git clone -q https://github.com/iangow/wrds2pg /private/var/folders/8g/9lwz95kd5wxdnhlvd6514ss00000gn/T/pip-req-build-rq_ek2li
Requirement already satisfied: pandas in /Users/iangow/miniforge3/lib/python3.9/site-packages (from wrds2pg==1.0.7) (1.2.3)
Requirement already satisfied: sqlalchemy in /Users/iangow/miniforge3/lib/python3.9/site-packages (from wrds2pg==1.0.7) (1.3.23)
Requirement already satisfied: paramiko in /Users/iangow/miniforge3/lib/python3.9/site-packages (from wrds2pg==1.0.7) (2.7.2)
Requirement already satisfied: psycopg2 in /Users/iangow/miniforge3/lib/python3.9/site-packages (from wrds2pg==1.0.7) (2.8.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/iangow/miniforge3/lib/python3.9/site-packages (from pandas->wrds2pg==1.0.7) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /Users/iangow/miniforge3/lib/python3.9/site-packages (from pandas->wrds2pg==1.0.7) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in /Users/iangow/miniforge3/lib/python3.9/site-packages (from pandas->wrds2pg==1.0.7) (1.20.2)
Requirement already satisfied: six>=1.5 in /Users/iangow/miniforge3/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas->wrds2pg==1.0.7) (1.15.0)
Requirement already satisfied: bcrypt>=3.1.3 in /Users/iangow/miniforge3/lib/python3.9/site-packages (from paramiko->wrds2pg==1.0.7) (3.2.0)
Requirement already satisfied: cryptography>=2.5 in /Users/iangow/miniforge3/lib/python3.9/site-packages (from paramiko->wrds2pg==1.0.7) (3.4.7)
Requirement already satisfied: pynacl>=1.0.1 in /Users/iangow/miniforge3/lib/python3.9/site-packages (from paramiko->wrds2pg==1.0.7) (1.4.0)
Requirement already satisfied: cffi>=1.1 in /Users/iangow/miniforge3/lib/python3.9/site-packages (from bcrypt>=3.1.3->paramiko->wrds2pg==1.0.7) (1.14.5)
Requirement already satisfied: pycparser in /Users/iangow/miniforge3/lib/python3.9/site-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko->wrds2pg==1.0.7) (2.20)
Building wheels for collected packages: wrds2pg
  Building wheel for wrds2pg (setup.py) ... done
  Created wheel for wrds2pg: filename=wrds2pg-1.0.7-py3-none-any.whl size=9427 sha256=040a3c893483d9d4ac6908553c6f5d3188fbfcb1035647514d7cd1ec0bf645f5
  Stored in directory: /private/var/folders/8g/9lwz95kd5wxdnhlvd6514ss00000gn/T/pip-ephem-wheel-cache-3i_8mxr6/wheels/58/1d/67/cbc1ee66c452d260f0c6d230621d87082f3beccf908f31470f
Successfully built wrds2pg
Installing collected packages: wrds2pg
Successfully installed wrds2pg-1.0.7
```

4. Tried updating table again. It works this time.
```
(base) iangow@Ians-Mac-mini wrds_pg % python                                           
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:00:30) 
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from wrds2pg import wrds_update
>>> wrds_update("dsi", "crsp")
Updated crsp.dsi is available.
Getting from WRDS.

Beginning file import at 13:43:30.
Importing data into crsp.dsi
Completed file import at 13:43:34.
True
>>> exit()
```

Note that WRDS doesn't get added to `known_hosts`. I guess a more secure approach would be to suggest that users log into the WRDS server via SSH and add the WRDS server to `known_hosts`. But I rate the security risk as low given the context.

```
(base) iangow@Ians-Mac-mini wrds_pg % vim ~/.ssh/known_hosts
```

**Comment by EvanJo** [comment]
Great documentation/comments! Also, this is tiny but it feels awesome to have made my first pull request on Git Hub!
