### ISSUE TITLE
Fail to get data from remote WRDS server 

### ISSUE THREAD

**Issue by MatixR** [iangow/wrds2pg#22]
Prof Ian Gow 
 Hi! Thanks for making easier research database .
Recently, I met a trouble for running your `wrds_update`.

As checked, I find the poblem comes from the function  `sas_to_pandas`.  

After run  ` p = get_process(sas_code, wrds_id, fpath)`(line 101 ),  it can not get the dataframe from the remote server by this line ` df = pd.read_csv(StringIO(p.read().decode(encoding)))` .

I checked the result of `p` and  `p.read().decode(encoding)`, and it seems that `p.read().decode `shows nothing.

I have spent many time to solve it , but failed.  I think maybe others would meet the same problem, so I open an issue to get your attention. 

By the way,  I use Mac OS, and this is the first time to use your program to built up a local database. 

Thank you again. 

The following shows how I use the function at termnal :

```

>>> wrds_update(table_name="mcti", schema = "crsp", host=os.getenv("PGHOST"), dbname=os.getenv("PGDATABASE"), wrds_id = wrds_id, force=True)

Forcing update based on user request.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/wrds2pg/wrds2pg.py", line 485, in wrds_update
    wrds_to_pg(table_name=table_name, schema=schema, engine=engine, wrds_id=wrds_id,
  File "/usr/local/lib/python3.9/site-packages/wrds2pg/wrds2pg.py", line 377, in wrds_to_pg
    make_table_data = get_table_sql(table_name=table_name, wrds_id=wrds_id,
  File "/usr/local/lib/python3.9/site-packages/wrds2pg/wrds2pg.py", line 163, in get_table_sql
    df = sas_to_pandas(sas_code, wrds_id, fpath)
  File "/usr/local/lib/python3.9/site-packages/wrds2pg/wrds2pg.py", line 104, in sas_to_pandas
    df = pd.read_csv(StringIO(p.read().decode(encoding)))
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
>>> 

```

**Comment by iangow** [comment]
The package works fine on MacOS (and Linux and I believe on Windows).

I suggest you run the line below with hard-code values for `host`, `dbname` and `wrds_id`.

```
(base) igow@Ians-Mac-mini ~ % python
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:35:11) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from wrds2pg import wrds_update
>>> wrds_update(table_name="mcti", schema = "crsp", host="localhost", dbname="crsp", wrds_id="iangow", force=True)
Forcing update based on user request.
Beginning file import at 13:45:05.
Importing data into crsp.mcti
Completed file import at 13:45:10.
True
```

**Comment by MatixR** [comment]
Prof Ian Gow, 

Thank you for your quick reply.

I run the code, and I still have the same errors. 
```
python3 
from wrds2pg import wrds_update
wrds_update(table_name="mcti", schema = "crsp", host="localhost", dbname="wrds", wrds_id="perry9", force=True)
```

Errors are: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/wrds2pg/wrds2pg.py", line 485, in wrds_update
    wrds_to_pg(table_name=table_name, schema=schema, engine=engine, wrds_id=wrds_id,
  File "/usr/local/lib/python3.9/site-packages/wrds2pg/wrds2pg.py", line 377, in wrds_to_pg
    make_table_data = get_table_sql(table_name=table_name, wrds_id=wrds_id,
  File "/usr/local/lib/python3.9/site-packages/wrds2pg/wrds2pg.py", line 163, in get_table_sql
    df = sas_to_pandas(sas_code, wrds_id, fpath)
  File "/usr/local/lib/python3.9/site-packages/wrds2pg/wrds2pg.py", line 104, in sas_to_pandas
    df = pd.read_csv(StringIO(p.read().decode(encoding)))
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

To make it more clear, I test the sub functions of your python package.  I run the code as follows. 
You can run it directly  cause I have changed the parameters for your convenience. 
I hope you can help me to solve it. Thank you very much. 

```
########################
#  Preparation 
########################


import wrds2pg
import paramiko
import io

import pandas as pd
from io import StringIO
import re, subprocess, os, paramiko
from time import gmtime, strftime
from sqlalchemy import create_engine
import sqlalchemy
from sqlalchemy.engine import reflection
from os import getenv

# Original function: sas_to_pandas
def sas_to_pandas(sas_code, wrds_id, fpath=None, encoding=None):
    """Function that runs SAS code on WRDS or local server
    and returns a Pandas data frame."""
    if not encoding:
        encoding = "utf-8"

    p = get_process(sas_code, wrds_id, fpath)                    # <<<< get_process(sas_code, wrds_id, fpath)  is the error source. 
   
    if wrds_id:
        df = pd.read_csv(StringIO(p.read().decode(encoding)))      # <<<<  p.read().decode(encoding) return   ''
    else:
        df = pd.read_csv(StringIO(p.read()))
    df.columns = map(str.lower, df.columns)
    p.close()

    return (df)


# Original function: get_process

def get_process(sas_code, wrds_id=None, fpath=None):
    if client:
        client.close()

    if wrds_id:
        """Function runs SAS code on WRDS server and
        returns result as pipe on stdout."""
        client.load_system_host_keys()
        client.set_missing_host_key_policy(paramiko.WarningPolicy())
        client.connect('wrds-cloud.wharton.upenn.edu',
                       username=wrds_id, compress=False)
        command = "qsas -stdio -noterminal"
        stdin, stdout, stderr = client.exec_command(command)
        stdin.write(sas_code)
        stdin.close()

        channel = stdout.channel
        # indicate that we're not going to write to that channel anymore
        channel.shutdown_write()
        return stdout

    elif fpath:

        p = subprocess.Popen(['sas', '-stdio', '-noterminal'],
                             stdin=subprocess.PIPE,
                             stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                             universal_newlines=True)
        p.stdin.write(sas_code)
        p.stdin.close()

        return p.stdout




########################
#  parameters setup 
########################

table_name="mcti" 

schema  = "crsp"
host    = "localhost"

# changed for you to run
dbname  = "crsp"         
wrds_id = "iangow"

# dbname  = "wrds"         
# wrds_id = "perry9"

fpath = None
rpath = None
drop  =""
keep  ="" 
rename ="" 
return_sql    =True
alt_table_name=None 
col_types     =None


#---------------------
# Make the SAS code 
#---------------------


# method01: 

if fpath:
    libname_stmt = "libname %s '%s';" % (schema, fpath)

elif rpath:
    libname_stmt = "libname %s '%s';" % (schema, rpath)
else:
    libname_stmt = ""

if not alt_table_name:
    alt_table_name = table_name


sas_template = """
    options nonotes nosource;
    %s

    * Use PROC CONTENTS to extract the information desired.;
    proc contents data=%s.%s(%s %s obs=1 %s) out=schema noprint;
    run;

    proc sort data=schema;
        by varnum;
    run;

    * Now dump it out to a CSV file;
    proc export data=schema(keep=name format formatl 
                                  formatd length type)
        outfile=stdout dbms=csv;
    run;
"""


if rename != '':
    rename_str = "rename=(" + rename + ") "
else:
    rename_str = ""

if drop != '':
    drop_str = "drop=" + drop
else:
    drop_str = ""

if keep != '':
    keep_str = "keep=" + keep
else:
    keep_str = ""

sas_code = sas_template % (libname_stmt, schema, table_name, drop_str, keep_str, rename_str)



# method2 for check SAS code
sas_code_02 = '\n        options nonotes nosource;\n        \n\n        * Use PROC CONTENTS to extract the information desired.;\n        proc contents data=crsp.mcti(  obs=1 ) out=schema noprint;\n        run;\n\n        proc sort data=schema;\n            by varnum;\n        run;\n\n        * Now dump it out to a CSV file;\n        proc export data=schema(keep=name format formatl \n                                      formatd length type)\n            outfile=stdout dbms=csv;\n        run;\n    '


#------------------------------------------------
# >>>> FIND THE ERROR : the funtion with problems
#-------------------------------------------------


# This does not work

df = sas_to_pandas(sas_code, wrds_id, fpath)

df = sas_to_pandas(sas_code_02, wrds_id, fpath)

		# Problem comes from:
		    # p = get_process(sas_code, wrds_id, fpath)                    # <<<< get_process(sas_code, wrds_id, fpath)  may be wrong 

		    # if wrds_id:
		    #     df = pd.read_csv(StringIO(p.read().decode(encoding)))   # <<<<  p.read().decode(encoding) return ''
		    # else:



#-------------------------------------------------
# >>>>FIND THE PROMBLEM : Step by step check 
#-------------------------------------------------



#  step01: Create the SSL link 
#-----------------------------

client = paramiko.SSHClient()

if client:
    client.close()

client.load_system_host_keys()  # the key can be loaded 
client.set_missing_host_key_policy(paramiko.WarningPolicy())

## I check the connection to wrds-cloud at terminal , it works.
client.connect('wrds-cloud.wharton.upenn.edu',
               username=wrds_id, compress=False)   
# I did not run the sascode          
command = "qsas -stdio -noterminal"
stdin, stdout, stderr = client.exec_command(command)    
stdin.write(sas_code)
stdin.close()

channel = stdout.channel
# indicate that we're not going to write to that channel anymore
channel.shutdown_write()


#  step02: define the p
#-----------------------------

# print(client)
# print(stout)

p = stdout   # the get_process() function return stdout        #<<<<<<<<<<<<<<<<<<<<<?????? ERROR

# print(stout)

#  step03: get the value from the server 
#-----------------------------

from io import StringIO 

enconding = None

if not encoding:
    encoding = "utf-8"

df = pd.read_csv(StringIO(p.read().decode(encoding)))   #<<<<<<<<<<<<<<<<<<<<<?????? ERROR

p.read()                     # return:   b''    #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<??    ERROR
 
p.read().decode(encoding)    # return:  ''      #<<<<<<<<<<<<<<<<<<<<<<<<<<<<??     ERROR


```
[Uploading wrds2pg_test.py…]()

**Comment by MatixR** [comment]
Prof Ian Gow,

I think I find why above errors occur.


I can directly log in wrds-cloud by typing `ssh XXXX@wrds-cloud.wharton.upenn.edu` on Tmerminal. This follows the way your mentioned to set up ~/.ssh/authorized_keys.  This shows as follows:

```
[xxxx@wrds-cloud-login1-w ~]$ more .ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDnN7MEzKNHDxsD1luZmkdSQTLL407AWvuHvusO7XiIKitQtm+jiub4M1EFhspdY9BOMskYLvXXA4FJHKdiTbWUu42E2SddZz4YX+CIr+bkWitFQGXU3sJAo+
AD3IyKny73ry7Cl/w4/Ti+ioWQoBZZljnWzKUNVHy5dnGDUOvjVzF3hDpYjEPh3COVnHTApVZRndeqSixdVPcU07eCiyNvl/dNZJAacF9ymQROb3lTgTaPZ4D  ....

```

However,  when use `qsas -stdio -noterminal` to subumit sas code, **the server asks to input the password**. 

It looks like:
```
[perry9@wrds-cloud-login1-w ~]$ qsas -stdio -noterminal
perry9@wrds-sas5-w.wharton.private's password: 

```

This interupts the process of uploading  `sas_code` to the server, leading to wrong value of `get_access()`function.  Specifically, those funcions return wrong results.
```
df = pd.read_csv(StringIO(p.read().decode(encoding)))   #<<<<<<<<<<<<<<<<<<<<<?????? ERROR

p.read()                     # return:   b''    #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<??    ERROR
 
p.read().decode(encoding)    # return:  ''      #<<<<<<<<<<<<<<<<<<<<<<<<<<<<??     ERROR

```


For the solutions,  **I have no idea why WRDS server still ask private's password**  after setting up the authorized_keys. 
If you know how to figure it out, show me some hints please. 

For now, I just use one more argument `password = xxxxxx` to connect to the server, and run the sas code. 

Sorry for bothering you with my trouble. 

Thank you for your effort.

Xuankai

**Comment by iangow** [comment]
From the WRDS server you might need to create an SSH key and put that into the list of authorised keys for `wrds-sas5-w.wharton.private` (in the same way you did for the WRDS server itself). Then `qsas` should work without a password.

**Comment by iangow** [comment]
Alternatively, ask WRDS for help with this issue. I'm not sure whether you're meant to enter a password to use `qsas` or not.

**Comment by MatixR** [comment]
Follow your advice, I have solved the error.  My `.ssh/authorized_keys` lost the `wrds-sas5-w.wharton.private`. I have created one. Thank you very much~~
